# Generated by Django 4.1.2 on 2022-11-04 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('parent_id', models.BigIntegerField()),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'category',
            },
        ),
    ]
