# Dynamic configuration
http:
  routers:
    dashboard:
      service: api@internal
      middlewares:
        - "user-auth"
      rule: "Host(`dash.yourdomain`)"
    kong:
      service: kong-service
      middlewares:
      rule: "Host(`kong.yourdomain`)"
    konga:
      service: konga-service
      middlewares:
      rule: "Host(`konga.yourdomain`)"      
  middlewares:
    secureHeaders:
      headers:
        sslRedirect: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
                
    # UserName : admin
    # Password : qwer1234          
    user-auth:
      basicAuth:
        users:
          - "admin:$apr1$tm53ra6x$FntXd6jcvxYM/YH0P2hcc1"
  services:
    kong-service:
      loadBalancer:
        servers:
          - url: "http://ip-address-of-kong:8000"
    konga-service:
      loadBalancer:
        servers:
          - url: "http://ip-address-of-konga:1337"          
tls:
  options:
    default:
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
      minVersion: VersionTLS12